name: destify_mobile
description: "Destify Mobile App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  animated_bottom_navigation_bar: ^1.3.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  flutter_animate: ^4.5.0
  image_picker: ^1.0.4
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  url_launcher: ^6.0.9
  font_awesome_flutter: ^10.5.0
  flutter_map: ^6.1.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/destinations/
    - assets/images/icons/
    - assets/images/placeholders/
    - assets/i18n/
